version: '3.8'

services:

  library_db:
    image: postgres:14
    volumes:
      - ./library_db:/docker-entrypoint-initdb.d/

    environment:
      - POSTGRES_DB=library_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_PORT=5432
      - PORT=8000
    ports:
      - "5432:5432"

  library_back:
    build:
      context: ./library_back
    restart: always
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

    volumes:
      - .:/backend
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=library_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_PORT=5432
      - PORT=8000
    depends_on:
      - library_db

  front-end:
    build:
      context: ./library_front
    container_name: library_front
    restart: always
    volumes:
      - ./:/library_front
      - /library_front/node_modules
      # - /visualeasy-front/.next
    ports:
      - "3000:3000"
