version: '3.8'

services:

  library_db:
    image: postgres:14
    volumes:
      - ./library_db:/docker-entrypoint-initdb.d/

    environment:
      - POSTGRES_DB=library_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_PORT=5432
      - PORT=8000
    ports:
      - "5432:5432"
